dist: xenial
language: csharp
solution: eform-ItemsGroupPlanningBase/Microting.ItemsGroupPlanningBase.sln
mono: none
dotnet: 3.1.101
addons:
  chrome: stable
  mariadb: '10.5'
script:
  - sudo mysql -e 'ALTER USER root@localhost IDENTIFIED VIA mysql_native_password'
  - dotnet build Microting.ItemsGroupPlanningBase.sln
  - dotnet test -v n Microting.ItemsGroupPlanningBase.Tests/Microting.ItemsGroupPlanningBase.Tests.csproj
  - export GITVERSION=`git describe --abbrev=0 --tags | cut -d "v" -f 2`
  - echo $GITVERSION
  - dotnet pack Microting.ItemsGroupPlanningBase.sln -c Release -o ./artifacts -p:PackageVersion=$GITVERSION
  - export FILENAME="/home/travis/build/microting/eform-items-group-planning-base/Microting.ItemsGroupPlanningBase/artifacts/Microting.ItemsGroupPlanningBase.${GITVERSION}.nupkg"
  - echo $FILENAME
  - dotnet nuget push $FILENAME -k $NUGET_SECRET_KEY -s https://api.nuget.org/v3/index.json || true
